require "formalist/elements/standard/check_box"
require "formalist/elements/standard/number_field"
require "formalist/elements/standard/radio_buttons"
require "formalist/elements/standard/select_box"
require "formalist/elements/standard/text_area"
